version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: luv-app-be
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://Nguyen:admin@cluster0.wq9d5yn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - luv-app-network
    volumes:
      - app_logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: luv-app-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - luv-app-network

volumes:
  app_logs:
    driver: local

networks:
  luv-app-network:
    driver: bridge
